In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('mlbootcamp5_train.csv', sep=';', 
                 index_col='id')

In [3]:
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
id,,,,,,,,,,,,
0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [4]:
df[df['gender'] == 1]['height'].mean(), \
df[df['gender'] == 2]['height'].mean()

(161.35561168460356, 169.94789538210054)

In [5]:
# 1 - ЖЕНЩИНЫ, 2 - МУЖЧИНЫ

In [6]:
df[df['gender'] == 1], \
df[df['gender'] == 2]

(         age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
 id
 1      20228       1     156    85.0    140     90            3     1      0
 2      18857       1     165    64.0    130     70            3     1      0
 4      17474       1     156    56.0    100     60            1     1      0
 8      21914       1     151    67.0    120     80            2     2      0
 9      22113       1     157    93.0    130     80            3     1      0
 13     17668       1     158    71.0    110     70            1     1      0
 14     19834       1     164    68.0    110     60            1     1      0
 15     22530       1     169    80.0    120     80            1     1      0
 21     19809       1     158    78.0    110     70            1     1      0
 25     21296       1     170    75.0    130     70            1     1      0
 27     16747       1     158    52.0    110     70            1     3      0
 28     17482       1     154    68.0    100     70            1     1      0
 31     21413       1     157    69.0    130     80            1     1      0
 32     23046       1     158    90.0    145     85            2     2      0
 35     16608       1     170    68.0    150     90            3     1      0
 36     14453       1     153    65.0    130    100            2     1      0
 37     19559       1     156    59.0    130     90            1     1      0
 38     18085       1     159    78.0    120     80            1     1      0
 42     18291       1     155   105.0    120     80            3     1      0
 43     23186       1     169    71.0    140     90            3     1      0
 44     14605       1     159    60.0    110     70            1     1      0
 45     20652       1     160    73.0    130     85            1     1      0
 47     20404       1     163    55.0    120     80            1     1      0
 51     17976       1     164    70.0    130     90            1     1      0
 53     18126       1     165    70.0    140     90            1     1      0
 54     19848       1     157    62.0    110     70            1     1      0
 56     18274       1     178    68.0    110     80            1     1      0
 59     19764       1     154    50.0    170     80            3     1      0
 60     17471       1     162    64.0    140     90            1     1      0
 61     18207       1     162   107.0    150     90            2     1      0
 ...      ...     ...     ...     ...    ...    ...          ...   ...    ...
 99932  22119       1     167    68.0    167     85            3     1      0
 99934  15254       1     158    55.0    110     70            1     1      0
 99935  19727       1     172    75.0    120     80            1     1      0
 99938  15151       1     170    60.0    120     80            2     1      0
 99939  21726       1     164    88.0    140     90            1     1      0
 99940  21453       1     158    75.0    120     80            3     3      0
 99945  19069       1     163    64.0    130     70            1     1      0
 99948  16598       1     161    50.0    110     75            1     1      0
 99949  21151       1     178    69.0    130     90            1     1      0
 99954  20327       1     156    67.0    140     80            2     1      0
 99960  17065       1     165    76.0    140     90            1     1      0
 99962  18226       1     168    75.0    120     80            1     1      0
 99964  21699       1     163    65.0    120     80            2     2      0
 99965  16843       1     168    75.0    120     79            1     1      0
 99967  18800       1     163    78.0     90     60            1     1      0
 99969  22423       1     163    74.0    160    100            2     2      0
 99973  18941       1     153    86.0    130     90            1     2      0
 99974  19652       1     165    72.0    120     80            1     1      0
 99977  18194       1     156   102.0    130     80            1     1      0
 99979  18852       1     151    49.0    120     80            1     1      0
 99981  21978       1     160    59.0    110     70            1     1      0
 99985  21013       1     157    83.0    120     70            1     1      0
 99986  15094       1     168    72.0    110     70            1     1      0
 99988  20609       1     159    72.0    130     90            2     2      0
 99990  18792       1     161    56.0    170     90            1     1      0
 99991  19699       1     172    70.0    130     90            1     1      0
 99992  21074       1     165    80.0    150     80            1     1      0
 99995  22601       1     158   126.0    140     90            2     2      0
 99998  22431       1     163    72.0    135     80            1     2      0
 99999  20540       1     170    72.0    120     80            2     1      0

        alco  active  cardio
 id
 1         0       1       1
 2         0       0       1
 4         0       0       0
 8         0       0       0
 9         0       1       0
 13        0       1       0
 14        0       0       0
 15        0       1       0
 21        0       1       0
 25        0       0       0
 27        0       1       0
 28        0       0       0
 31        0       1       0
 32        0       1       1
 35        0       1       1
 36        0       1       0
 37        0       1       0
 38        0       1       0
 42        0       1       1
 43        0       1       1
 44        0       1       0
 45        0       0       1
 47        0       1       0
 51        0       1       0
 53        0       1       1
 54        0       0       0
 56        0       1       1
 59        0       1       1
 60        0       1       1
 61        0       1       1
 ...     ...     ...     ...
 99932     0       1       1
 99934     0       1       0
 99935     0       1       1
 99938     0       1       0
 99939     0       1       0
 99940     0       1       0
 99945     0       1       1
 99948     0       1       0
 99949     0       1       1
 99954     0       0       0
 99960     0       1       1
 99962     0       1       0
 99964     0       1       0
 99965     0       1       0
 99967     0       1       1
 99969     0       1       1
 99973     0       1       1
 99974     0       1       0
 99977     1       0       1
 99979     0       1       0
 99981     0       1       0
 99985     0       1       1
 99986     0       1       1
 99988     0       1       0
 99990     0       1       1
 99991     0       1       1
 99992     0       1       1
 99995     0       1       1
 99998     0       0       1
 99999     0       1       0

 [45530 rows x 12 columns],
          age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
 id
 0      18393       2     168    62.0    110     80            1     1      0
 3      17623       2     169    82.0    150    100            1     1      0
 12     22584       2     178    95.0    130     90            3     3      0
 16     18815       2     173    60.0    120     80            1     1      0
 18     14791       2     165    60.0    120     80            1     1      0
 23     14532       2     181    95.0    130     90            1     1      1
 24     16782       2     172   112.0    120     80            1     1      0
 29     21755       2     162    56.0    120     70            1     1      1
 30     19778       2     163    83.0    120     80            1     1      0
 33     23376       2     156    45.0    110     60            1     1      0
 39     14574       2     166    66.0    120     80            1     1      0
 40     21057       2     169    74.0    130     70            1     3      0
 46     21940       2     173    82.0    140     90            3     1      0
 49     18328       2     175    95.0    120     80            1     1      0
 52     23388       2     162    72.0    130     80            1     1      1
 57     21475       2     171    69.0    140     90            1     1      0
 58     20556       2     159    63.0    120     60            1     1      0
 62     18535       2     168    69.0    120     80            1     1      0
 63     16864       2     175    70.0    120     80            2     1      0
 67     19575       2     166    85.0    150    100            1     1      0
 70     21787       2     165    73.0    125     90            1     1      0
 73     15901       2     172    84.0    140     90            1     1      1
 79     20960       2     165    75.0    180     90            3     1      0
 81     20330       2     187   115.0    130     90            1     1      0
 86     20649       2     169    71.0    120     80            1     1      0
 88     19148       2     170    69.0    130     80            1     1      0
 90     22099       2     171    97.0    150    100            3     1      1
 96     21874       2     179    95.0    150     90            1     1      0
 103    16039       2     180    90.0    140     90            2     2      0
 105    20397       2     188   105.0    120     80            1     1      0
 ...      ...     ...     ...     ...    ...    ...          ...   ...    ...
 99884  19438       2     175    80.0    120     80            1     1      0
 99896  22609       2     166    64.0    120     80            1     3      0
 99897  15243       2     171    67.0    110     60            1     1      0
 99904  18428       2     168    64.0    110     70            1     1      0
 99906  23413       2     171    70.0    140     90            1     1      0
 99910  20962       2     174    83.0    120     80            3     1      0
 99919  22570       2     160    55.0    140     90            2     1      0
 99922  23464       2     170    97.0    130     90            2     1      0
 99930  23305       2     172   113.0    110     80            1     1      0
 99933  19137       2     167    74.0    130     80            1     1      1
 99936  17373       2     173    69.0    110     70            1     1      1
 99941  15536       2     166    90.0    120     80            1     1      1
 99943  15239       2     169    67.0    160     90            1     1      0
 99947  20587       2     169    79.0    140     90            1     1      0
 99950  19538       2     155    76.0    130     90            1     1      0
 99951  22491       2     170    72.0    120     80            1     1      0
 99952  15450       2     165    66.0    120     80            1     1      0
 99955  21416       2     168    63.0    140   1000            1     1      0
 99956  16093       2     157    61.0    110     90            1     1      0
 99957  20529       2     175    78.0    120     80            1     1      0
 99958  22572       2     173   103.0    140     80            3     1      1
 99959  20136       2     177    80.0    130     80            1     1      0
 99961  22142       2     175    72.0    130     80            1     1      0
 99963  21264       2     182   100.0    120     80            1     1      0
 99971  17727       2     167    69.0    110     80            1     1      0
 99972  17500       2     182   110.0    130     90            2     2      0
 99975  17926       2     168    80.0    120     80            1     1      0
 99978  18198       2     180    78.0    120     80            1     1      0
 99993  19240       2     168    76.0    120     80            1     1      1
 99996  19066       2     183   105.0    180     90            3     1      0

        alco  active  cardio
 id
 0         0       1       0
 3         0       1       1
 12        0       1       1
 16        0       1       0
 18        0       0       0
 23        1       1       0
 24        0       0       1
 29        0       1       0
 30        0       1       0
 33        0       1       0
 39        0       1       0
 40        0       0       0
 46        0       0       1
 49        0       1       0
 52        0       1       1
 57        0       1       1
 58        0       1       1
 62        0       0       0
 63        0       1       0
 67        0       1       1
 70        0       0       0
 73        0       1       1
 79        0       1       1
 81        1       1       0
 86        0       1       1
 88        0       1       0
 90        0       1       1
 96        0       1       1
 103       0       0       0
 105       0       1       1
 ...     ...     ...     ...
 99884     0       1       1
 99896     0       1       1
 99897     0       1       0
 99904     0       1       0
 99906     0       1       0
 99910     0       1       1
 99919     0       1       1
 99922     0       1       1
 99930     0       0       1
 99933     1       1       0
 99936     1       1       1
 99941     0       1       0
 99943     0       1       1
 99947     0       0       1
 99950     0       1       0
 99951     0       0       1
 99952     0       0       0
 99955     0       1       1
 99956     0       1       0
 99957     0       0       0
 99958     1       0       1
 99959     0       1       0
 99961     0       1       0
 99963     0       1       1
 99971     1       0       0
 99972     0       1       1
 99975     0       1       1
 99978     0       1       0
 99993     0       1       0
 99996     1       0       1

 [24470 rows x 12 columns])

In [7]:
# 45530 женщин и 24470 мужчин

In [8]:
df[(df['gender'] == 1) & (df['alco'] == 1)], \
df[(df['gender'] == 2) & (df['alco'] == 1)]

(         age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
 id
 134    17363       1     167    71.0    120     80            2     1      0
 136    18718       1     167    80.0    190     90            2     1      0
 199    18068       1     160    90.0    130     90            1     1      0
 213    16028       1     157    69.0    120     80            1     1      0
 511    23444       1     175    76.0    120     80            1     1      0
 697    15975       1     158    69.0    110     80            1     3      0
 771    19650       1     164    85.0    145     90            1     1      0
 810    14824       1     165    80.0    120     90            1     1      0
 1029   21126       1     164    77.0    110     80            1     2      0
 1092   21292       1     160    90.0    147     84            2     1      0
 1144   19835       1     166    73.0    110     70            2     1      0
 1266   23350       1     159    60.0    130     80            3     2      0
 1326   18369       1     167    81.0    120     80            2     1      0
 1348   20959       1     160    65.0    120     80            1     2      0
 1369   19554       1     158    87.0    130     90            1     1      0
 1621   19645       1     155    78.0    126     82            1     1      0
 1626   19931       1     163    73.0    160     80            1     1      0
 1655   18251       1     152   109.0    105     65            2     1      0
 2006   16874       1     153    65.0    100     60            1     1      0
 2047   16803       1     156    74.0    130     90            1     1      1
 2067   20264       1     156    52.0    100     70            1     1      0
 2115   23614       1     157    78.0    110     80            1     1      1
 2125   18954       1     165   105.0    160     80            1     1      0
 2164   20193       1     171    76.0    120     80            1     1      0
 2254   19764       1     164    68.0    120     90            2     1      0
 2265   15323       1     164    65.0    130     90            1     1      0
 2360   19560       1     182    92.0    145     90            1     1      0
 2587   19718       1     170    75.0    130     90            3     3      0
 2625   23253       1     157    60.0    120     80            1     1      0
 3037   18254       1     160    71.0    120     80            1     1      0
 ...      ...     ...     ...     ...    ...    ...          ...   ...    ...
 96452  23202       1     158    88.0    170    100            3     1      0
 96465  22581       1     153    80.0    130     80            1     1      0
 96635  17503       1     156    59.0    120     70            1     1      1
 96778  14601       1     160    63.0    120     80            1     1      0
 96828  19300       1     156    82.0    120     80            1     1      0
 97027  14870       1     156    77.0    120     80            2     2      0
 97151  21701       1     154    64.0     85     66            1     1      0
 97208  16787       1     178    68.0    140     90            2     1      0
 97389  21106       1     166    73.0    130     80            2     1      0
 97555  16215       1     162   105.0    110     80            2     1      0
 97611  18217       1     164   100.0    130     90            1     2      0
 97765  21991       1     145    60.0    130     90            3     3      0
 97911  19689       1     160    64.5    130     80            3     1      1
 97953  22579       1     170    67.0    120     80            1     1      0
 98049  18129       1     157    70.0    120     90            2     1      0
 98307  16831       1     166    91.0    130     80            3     1      0
 98504  21679       1     161   107.0    170    100            3     1      0
 98625  15940       1     165    64.0    120     80            1     1      0
 98663  22029       1     152    85.0     90     60            1     1      0
 98734  19487       1     164    89.0    140     90            3     1      0
 98758  22070       1     168    68.0    140     80            1     1      0
 98846  18263       1     158    68.0    119     67            2     2      0
 98944  15248       1     155    45.0    120     60            1     1      1
 99239  21211       1     165    69.0    140     90            1     1      1
 99305  14446       1     160    63.0    160   1000            2     1      0
 99507  14925       1     170   111.0    160     90            2     1      0
 99562  21357       1     144   115.0    140     90            1     1      0
 99606  15793       1     163    90.0    125     80            1     1      0
 99882  23281       1     164    98.0    140     90            2     1      0
 99977  18194       1     156   102.0    130     80            1     1      0

        alco  active  cardio
 id
 134       1       1       1
 136       1       0       0
 199       1       1       0
 213       1       1       1
 511       1       1       1
 697       1       1       0
 771       1       1       1
 810       1       0       1
 1029      1       1       0
 1092      1       1       1
 1144      1       1       0
 1266      1       1       1
 1326      1       1       0
 1348      1       0       1
 1369      1       1       0
 1621      1       1       0
 1626      1       1       1
 1655      1       1       0
 2006      1       1       0
 2047      1       1       1
 2067      1       1       0
 2115      1       1       1
 2125      1       1       1
 2164      1       1       1
 2254      1       1       0
 2265      1       1       0
 2360      1       1       1
 2587      1       0       1
 2625      1       1       1
 3037      1       1       0
 ...     ...     ...     ...
 96452     1       1       1
 96465     1       0       1
 96635     1       1       0
 96778     1       1       0
 96828     1       1       0
 97027     1       1       0
 97151     1       1       0
 97208     1       1       1
 97389     1       1       0
 97555     1       1       0
 97611     1       1       0
 97765     1       1       1
 97911     1       0       1
 97953     1       1       1
 98049     1       0       1
 98307     1       1       0
 98504     1       1       1
 98625     1       0       0
 98663     1       0       0
 98734     1       1       1
 98758     1       1       1
 98846     1       1       0
 98944     1       0       0
 99239     1       1       1
 99305     1       0       1
 99507     1       0       1
 99562     1       0       1
 99606     1       0       0
 99882     1       1       1
 99977     1       0       1

 [1161 rows x 12 columns],
          age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
 id
 23     14532       2     181    95.0    130     90            1     1      1
 81     20330       2     187   115.0    130     90            1     1      0
 142    14499       2     164    48.0    110     70            1     2      1
 180    21473       2     174    90.0    140     80            1     1      1
 240    21848       2     170    69.0    120     80            1     1      1
 318    23376       2     175    75.0    180    100            3     1      1
 321    18444       2     173    75.0    130     80            2     1      1
 410    22415       2     173    70.0    130     70            2     1      1
 461    16069       2     160    85.0    120     80            1     1      0
 525    15215       2     172    71.0    160    120            3     3      1
 546    15912       2     171    74.0    120     80            1     1      1
 581    23262       2     162    70.0    130     70            1     1      1
 630    18978       2     175    86.0    120     80            1     1      1
 662    21993       2     175    92.0    120     80            3     1      1
 683    18825       2     164    68.0    140    100            1     1      0
 779    21159       2     160    55.0    120     80            1     1      1
 812    16488       2     175    95.0    120     90            1     1      1
 817    17420       2     175    88.0    140     90            2     1      1
 892    16018       2     166    58.0    125     80            1     1      1
 946    21094       2     167    90.0    130     85            2     2      1
 958    18265       2     168    75.0    110     80            1     1      1
 982    21101       2     170    90.0    110     70            1     1      1
 991    14549       2     165    85.0    120     80            1     1      1
 1032   21652       2     167    70.0    160     90            2     1      1
 1075   16208       2     179    87.0    140     78            1     1      1
 1194   23473       2     164    74.0    120     80            1     1      1
 1237   15297       2     170    65.0    120     80            1     1      1
 1275   22722       2     160    57.0    150     80            1     2      1
 1278   19890       2     163    71.0    130     80            1     1      1
 1310   19764       2     175    82.0    150    100            2     2      1
 ...      ...     ...     ...     ...    ...    ...          ...   ...    ...
 98942  19073       2     175    67.0    140    100            1     1      1
 98945  15355       2     165   101.0    120     90            1     1      1
 98948  18709       2     169    76.0    130     80            1     2      1
 99039  17260       2     167    65.0    120     80            1     1      0
 99121  20230       2     165    72.0    140     90            1     1      1
 99251  16508       2     168    64.0    130     80            1     1      1
 99360  21023       2     177    85.0    110     80            1     1      0
 99401  18286       2     192    83.0    110     70            1     1      0
 99405  16781       2     179    93.0    180    100            1     2      0
 99412  21141       2     168    65.0    120     90            1     1      0
 99421  23334       2     182    89.0    140     90            3     1      0
 99437  23408       2     170    85.0    125     90            1     1      0
 99480  18377       2     156    60.0    110     90            1     1      1
 99551  23224       2     151    45.0    120     70            3     1      1
 99561  21116       2     170    68.0    115     70            1     1      0
 99640  16809       2     177    72.0    120     80            1     1      1
 99669  19250       2     158    72.0    140     90            1     1      0
 99686  19606       2     170    77.0    150     80            1     1      1
 99724  19013       2     175    98.0    130     80            2     1      0
 99759  16006       2     179    76.0    140     90            3     2      0
 99763  22643       2     161    66.0    130     80            1     1      0
 99779  17256       2     173    70.0    130     80            1     1      1
 99799  19736       2     188   108.0    130     80            2     2      0
 99858  19475       2     171    65.0    120     80            1     1      1
 99864  21883       2     178   102.0    150    100            1     2      0
 99933  19137       2     167    74.0    130     80            1     1      1
 99936  17373       2     173    69.0    110     70            1     1      1
 99958  22572       2     173   103.0    140     80            3     1      1
 99971  17727       2     167    69.0    110     80            1     1      0
 99996  19066       2     183   105.0    180     90            3     1      0

        alco  active  cardio
 id
 23        1       1       0
 81        1       1       0
 142       1       1       1
 180       1       0       1
 240       1       1       0
 318       1       1       1
 321       1       0       0
 410       1       1       0
 461       1       1       0
 525       1       0       1
 546       1       1       0
 581       1       1       1
 630       1       0       0
 662       1       1       1
 683       1       1       1
 779       1       1       0
 812       1       1       1
 817       1       0       1
 892       1       1       0
 946       1       1       0
 958       1       1       0
 982       1       1       0
 991       1       1       0
 1032      1       1       1
 1075      1       1       1
 1194      1       0       1
 1237      1       1       0
 1275      1       1       0
 1278      1       1       0
 1310      1       1       1
 ...     ...     ...     ...
 98942     1       1       1
 98945     1       1       1
 98948     1       1       1
 99039     1       1       0
 99121     1       1       1
 99251     1       0       0
 99360     1       0       0
 99401     1       0       0
 99405     1       1       1
 99412     1       0       0
 99421     1       1       1
 99437     1       1       1
 99480     1       1       0
 99551     1       0       1
 99561     1       1       0
 99640     1       1       0
 99669     1       1       1
 99686     1       1       1
 99724     1       1       0
 99759     1       1       1
 99763     1       1       0
 99779     1       1       0
 99799     1       0       1
 99858     1       1       0
 99864     1       0       1
 99933     1       1       0
 99936     1       1       1
 99958     1       0       1
 99971     1       0       0
 99996     1       0       1

 [2603 rows x 12 columns])

In [9]:
# Женщины - 1161 < МужчинЫ - 2603

In [17]:
for gender, sub_df in df.groupby('gender'):
    print(gender)
    print(sub_df['smoke'].mean())

1
0.017856358445
2
0.218880261545

In [15]:
print(0.22/0.018)

12.222222222222223

In [16]:
# В 12 раз

In [19]:
for smoke, sub_df in df.groupby('smoke'):
    print(smoke)
    print(sub_df['age'].median())

0
19722.0
1
19125.0

In [21]:
print((19722 - 19125)/30)

19.9

In [22]:
# На 20 месяцев

In [23]:
df['age_years'] = round(df['age']/30/12)

In [34]:
sub = df[(df['age_years'] > 60) & (df['age_years'] <=64) & (df['gender'] == 2) & (df['smoke'] == 1)]

In [35]:
first = sub[(sub['ap_hi'] <= 120) & (sub['cholesterol'] == 1)]

In [37]:
second = sub[(sub['ap_hi'] >= 160) & (sub['ap_hi'] < 180) & (sub['cholesterol'] == 3)]

In [39]:
first[first['cardio'] == 1]

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years
id,,,,,,,,,,,,,
1312,22408,2,164,68.0,120,80,1,1,1,0,1,1,62.0
3082,22704,2,174,65.0,110,50,1,1,1,0,1,1,63.0
5471,22566,2,158,68.0,120,80,1,1,1,0,1,1,63.0
6690,22552,2,175,69.0,110,80,1,1,1,0,1,1,63.0
11663,21971,2,165,70.0,110,80,1,1,1,1,1,1,61.0
12584,21990,2,170,82.0,120,80,1,1,1,0,1,1,61.0
17722,22447,2,168,71.0,120,80,1,1,1,0,0,1,62.0
18451,22761,2,164,60.0,120,80,1,1,1,0,0,1,63.0
21607,22668,2,151,92.0,120,80,1,1,1,0,1,1,63.0
21690,22132,2,168,74.0,120,80,1,1,1,0,1,1,61.0
24208,22848,2,174,80.0,120,80,1,1,1,0,1,1,63.0
24349,21832,2,170,74.0,120,80,1,1,1,0,0,1,61.0
25675,22691,2,168,74.0,120,80,1,1,1,1,0,1,63.0
27183,22507,2,180,70.0,120,80,1,1,1,1,0,1,63.0
28040,21832,2,167,86.0,120,80,1,1,1,0,1,1,61.0
30794,22683,2,166,71.0,120,80,1,3,1,0,1,1,63.0
33171,22496,2,154,89.0,120,80,1,1,1,1,1,1,62.0
33928,22768,2,172,82.0,110,60,1,1,1,0,1,1,63.0
34280,22671,2,180,70.0,120,80,1,1,1,0,0,1,63.0
35226,21877,2,178,93.0,110,70,1,1,1,1,1,1,61.0
37027,21930,2,162,71.0,110,80,1,1,1,0,1,1,61.0
38395,23093,2,165,76.0,110,80,1,1,1,0,1,1,64.0
38440,21842,2,165,66.0,110,70,1,1,1,0,1,1,61.0
40082,22972,2,160,75.0,110,71,1,1,1,0,0,1,64.0
43209,22704,2,177,75.0,120,80,1,1,1,0,0,1,63.0
43564,21866,2,169,75.0,110,80,1,2,1,1,1,1,61.0
49823,23203,2,170,66.0,120,80,1,1,1,0,1,1,64.0
50613,22046,2,168,70.0,120,70,1,1,1,0,1,1,61.0
50614,22933,2,174,86.0,120,80,1,1,1,0,0,1,64.0
51042,22404,2,179,85.0,120,80,1,1,1,0,0,1,62.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63813,21966,2,175,59.0,120,60,1,1,1,0,1,1,61.0
65653,23061,2,167,72.0,120,90,1,1,1,0,0,1,64.0
65840,23116,2,190,89.0,120,80,1,1,1,0,1,1,64.0
66359,22058,2,169,73.0,120,80,1,1,1,0,1,1,61.0
71199,21909,2,163,67.0,120,80,1,1,1,0,1,1,61.0
71244,22640,2,172,89.0,120,80,1,1,1,0,0,1,63.0
75155,21789,2,170,57.0,120,80,1,1,1,1,0,1,61.0
75204,21945,2,167,86.0,110,80,1,1,1,0,1,1,61.0
76361,22561,2,170,70.0,110,70,1,1,1,0,1,1,63.0
76777,22476,2,163,80.0,120,80,1,1,1,0,1,1,62.0
77395,22038,2,174,76.0,120,80,1,1,1,0,1,1,61.0
80829,21815,2,172,76.0,110,70,1,1,1,0,1,1,61.0
81336,21852,2,165,80.0,100,60,1,1,1,0,1,1,61.0
82307,22416,2,178,69.0,120,80,1,1,1,1,1,1,62.0
83362,22714,2,170,81.0,120,80,1,1,1,0,1,1,63.0
83605,22435,2,171,89.0,120,80,1,1,1,0,1,1,62.0
83740,22596,2,162,65.0,110,70,1,1,1,1,1,1,63.0
85455,22701,2,175,82.0,120,80,1,1,1,1,1,1,63.0
86369,21913,2,160,88.0,120,80,1,1,1,1,1,1,61.0
87273,23149,2,170,84.0,120,80,1,1,1,0,0,1,64.0
91430,22843,2,174,85.0,120,80,1,1,1,0,0,1,63.0
91667,22534,2,166,90.0,120,80,1,1,1,0,0,1,63.0
91965,22482,2,174,52.0,120,80,1,1,1,0,1,1,62.0
92400,21809,2,164,81.0,120,80,1,3,1,1,0,1,61.0
92747,21819,2,168,65.0,120,80,1,1,1,0,1,1,61.0
96461,21875,2,170,80.0,120,90,1,1,1,0,1,1,61.0
96920,21970,2,172,94.0,110,70,1,2,1,0,1,1,61.0
97026,22174,2,179,77.0,120,80,1,1,1,0,1,1,62.0
97363,21977,2,170,72.0,120,80,1,1,1,0,1,1,61.0
98834,23210,2,160,68.0,120,90,1,1,1,1,1,1,64.0

In [40]:
second[second['cardio'] == 1]

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years
id,,,,,,,,,,,,,
6382,21891,2,160,64.0,160,90,3,1,1,0,1,1,61.0
8972,22859,2,167,66.0,170,80,3,1,1,1,1,1,63.0
18870,21856,2,164,83.0,160,100,3,1,1,0,0,1,61.0
28497,21980,2,171,81.0,170,90,3,1,1,0,1,1,61.0
38592,22608,2,170,80.0,160,80,3,1,1,0,1,1,63.0
49988,22729,2,170,86.0,170,1000,3,3,1,0,1,1,63.0
50125,22640,2,165,85.0,160,90,3,3,1,1,1,1,63.0
59072,21975,2,174,90.0,160,100,3,1,1,1,1,1,61.0
67310,21912,2,179,78.0,160,90,3,1,1,0,1,1,61.0
69326,22117,2,168,66.0,160,90,3,1,1,0,1,1,61.0
70518,23170,2,173,100.0,160,90,3,1,1,0,0,1,64.0
75777,22361,2,168,75.0,160,1000,3,3,1,0,1,1,62.0
77266,22003,2,172,90.0,160,100,3,1,1,0,1,1,61.0
78663,21893,2,170,77.0,160,100,3,1,1,1,1,1,61.0
79043,23107,2,182,78.0,160,90,3,2,1,0,1,1,64.0
82548,22621,2,172,70.0,160,90,3,1,1,1,1,1,63.0

In [41]:
print(round(63/16))

4

In [42]:
# В 4 раза

In [55]:
df['BMI'] = df['weight']/((df['height']/100)**2)

In [56]:
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,BMI
id,,,,,,,,,,,,,,
0,18393,2,168,62.0,110,80,1,1,0,0,1,0,51.0,21.967120
1,20228,1,156,85.0,140,90,3,1,0,0,1,1,56.0,34.927679
2,18857,1,165,64.0,130,70,3,1,0,0,0,1,52.0,23.507805
3,17623,2,169,82.0,150,100,1,1,0,0,1,1,49.0,28.710479
4,17474,1,156,56.0,100,60,1,1,0,0,0,0,49.0,23.011177

In [57]:
df[df['cardio'] == 0]['BMI'].mean(), \
df[df['cardio'] == 1]['BMI'].mean()

(26.5481752067945, 28.56606062701535)

In [58]:
df['BMI'].median()

26.374068120774975

In [60]:
df[df['gender'] == 1]['BMI'].mean(), \
df[df['gender'] == 2]['BMI'].mean()

(27.98758344183285, 26.754442357289356)

In [61]:
# У женщин в среднем BMI выше, чем у мужчин

In [103]:
df2 = df[(df['ap_hi'] >= df['ap_lo']) & (df['height'] > df['height'].quantile(0.025)) & (df['height'] < df['height'].quantile(0.975)) & (df['weight'] > df['weight'].quantile(0.025)) & (df['weight'] < df['weight'].quantile(0.975))]

In [104]:
df2

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,BMI
id,,,,,,,,,,,,,,
0,18393,2,168,62.0,110,80,1,1,0,0,1,0,51.0,21.967120
1,20228,1,156,85.0,140,90,3,1,0,0,1,1,56.0,34.927679
2,18857,1,165,64.0,130,70,3,1,0,0,0,1,52.0,23.507805
3,17623,2,169,82.0,150,100,1,1,0,0,1,1,49.0,28.710479
4,17474,1,156,56.0,100,60,1,1,0,0,0,0,49.0,23.011177
8,21914,1,151,67.0,120,80,2,2,0,0,0,0,61.0,29.384676
9,22113,1,157,93.0,130,80,3,1,0,0,1,0,61.0,37.729725
12,22584,2,178,95.0,130,90,3,3,0,0,1,1,63.0,29.983588
13,17668,1,158,71.0,110,70,1,1,0,0,1,0,49.0,28.440955
14,19834,1,164,68.0,110,60,1,1,0,0,0,0,55.0,25.282570
15,22530,1,169,80.0,120,80,1,1,0,0,1,0,63.0,28.010224
16,18815,2,173,60.0,120,80,1,1,0,0,1,0,52.0,20.047446
18,14791,2,165,60.0,120,80,1,1,0,0,0,0,41.0,22.038567
21,19809,1,158,78.0,110,70,1,1,0,0,1,0,55.0,31.244993
25,21296,1,170,75.0,130,70,1,1,0,0,0,0,59.0,25.951557
27,16747,1,158,52.0,110,70,1,3,0,0,1,0,47.0,20.829995
28,17482,1,154,68.0,100,70,1,1,0,0,0,0,49.0,28.672626
29,21755,2,162,56.0,120,70,1,1,1,0,1,0,60.0,21.338211
30,19778,2,163,83.0,120,80,1,1,0,0,1,0,55.0,31.239414
31,21413,1,157,69.0,130,80,1,1,0,0,1,0,59.0,27.993022
32,23046,1,158,90.0,145,85,2,2,0,0,1,1,64.0,36.051915
35,16608,1,170,68.0,150,90,3,1,0,0,1,1,46.0,23.529412
36,14453,1,153,65.0,130,100,2,1,0,0,1,0,40.0,27.767098
37,19559,1,156,59.0,130,90,1,1,0,0,1,0,54.0,24.243918
38,18085,1,159,78.0,120,80,1,1,0,0,1,0,50.0,30.853210
39,14574,2,166,66.0,120,80,1,1,0,0,1,0,40.0,23.951227
40,21057,2,169,74.0,130,70,1,3,0,0,0,0,58.0,25.909457
42,18291,1,155,105.0,120,80,3,1,0,0,1,1,51.0,43.704475
43,23186,1,169,71.0,140,90,3,1,0,0,1,1,64.0,24.859074
44,14605,1,159,60.0,110,70,1,1,0,0,1,0,41.0,23.733238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99950,19538,2,155,76.0,130,90,1,1,0,0,1,0,54.0,31.633715
99951,22491,2,170,72.0,120,80,1,1,0,0,0,1,62.0,24.913495
99952,15450,2,165,66.0,120,80,1,1,0,0,0,0,43.0,24.242424
99954,20327,1,156,67.0,140,80,2,1,0,0,0,0,56.0,27.531229
99956,16093,2,157,61.0,110,90,1,1,0,0,1,0,45.0,24.747454
99957,20529,2,175,78.0,120,80,1,1,0,0,0,0,57.0,25.469388
99958,22572,2,173,103.0,140,80,3,1,1,1,0,1,63.0,34.414782
99959,20136,2,177,80.0,130,80,1,1,0,0,1,0,56.0,25.535446
99960,17065,1,165,76.0,140,90,1,1,0,0,1,1,47.0,27.915519
99961,22142,2,175,72.0,130,80,1,1,0,0,1,0,62.0,23.510204
99962,18226,1,168,75.0,120,80,1,1,0,0,1,0,51.0,26.573129
99964,21699,1,163,65.0,120,80,2,2,0,0,1,0,60.0,24.464602
99965,16843,1,168,75.0,120,79,1,1,0,0,1,0,47.0,26.573129
99967,18800,1,163,78.0,90,60,1,1,0,0,1,1,52.0,29.357522
99969,22423,1,163,74.0,160,100,2,2,0,0,1,1,62.0,27.852008
99971,17727,2,167,69.0,110,80,1,1,0,1,0,0,49.0,24.740937
99973,18941,1,153,86.0,130,90,1,2,0,0,1,1,53.0,36.738007
99974,19652,1,165,72.0,120,80,1,1,0,0,1,0,55.0,26.446281
99975,17926,2,168,80.0,120,80,1,1,0,0,1,1,50.0,28.344671
99977,18194,1,156,102.0,130,80,1,1,0,1,0,1,51.0,41.913215
99981,21978,1,160,59.0,110,70,1,1,0,0,1,0,61.0,23.046875
99985,21013,1,157,83.0,120,70,1,1,0,0,1,1,58.0,33.672766
99986,15094,1,168,72.0,110,70,1,1,0,0,1,1,42.0,25.510204
99988,20609,1,159,72.0,130,90,2,2,0,0,1,0,57.0,28.479886
99990,18792,1,161,56.0,170,90,1,1,0,0,1,1,52.0,21.604105
99991,19699,1,172,70.0,130,90,1,1,0,0,1,1,55.0,23.661439
99992,21074,1,165,80.0,150,80,1,1,0,0,1,1,59.0,29.384757
99993,19240,2,168,76.0,120,80,1,1,1,0,1,0,53.0,26.927438
99998,22431,1,163,72.0,135,80,1,2,0,0,0,1,62.0,27.099251
99999,20540,1,170,72.0,120,80,2,1,0,0,1,0,57.0,24.913495

In [106]:
print(round((70000 - 61204)/70000*100))

13

In [ ]:
# 13 процентов данных откинуто